# File: .github/workflows/workflow.yml

<TODO Trigger Clause>

<TODO Name Clause>

jobs:

  deploy:
    <TODO VM Image Clause>
    steps:
    
    - name: debug secrets
      run: |
        echo "${{ secrets.RG }}"                | sed -r 's/(.)/\1 /g'
        echo "${{ secrets.ASP }}"               | sed -r 's/(.)/\1 /g'
        echo "${{ secrets.WEBAPP }}"            | sed -r 's/(.)/\1 /g'
        echo "${{ secrets.LOC }}"               | sed -r 's/(.)/\1 /g'
        echo "${{ secrets.AZURE_CREDENTIALS }}" | sed -r 's/(.)/\1 /g'
    
    <TODO Azure Login Step>
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          <TODO Azure CLI Service Plan>
          <TODO Azure CLI WebApp>
